### ISSUE TITLE
Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. 

### ISSUE THREAD

**Issue by VarunKota** [NoviceMAn-prog/MSRF-Net#32]
2022-05-25 05:23:33.867451: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.

I'm facing this error while trying to run the model.py on Colab

**Comment by augustoicaro** [comment]
The original code is a mess. I suggest you to use my fork or the pytorch implementation shared in the issues.

**Comment by wjn0807** [comment]
I'm facing an error like this  while trying to run the test.py on Colab.  Do you know how to solve this error now? Can you teach me?  
W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.

**Comment by augustoicaro** [comment]
Did you try my fork? https://github.com/augustoicaro/MSRF-Net

You should also look for the improved version called GMSRF-Net from the same authors.
